import { SitemapStream, streamToPromise } from 'sitemap';
import { createWriteStream, readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { writeFileSync } from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Site configuration
const SITE_URL = 'https://wordcounterplusapp.com';
const DIST_PUBLIC_PATH = join(__dirname, 'dist', 'public');

// Function to get static pages
function getStaticPages() {
  const staticRoutes = [
    { page: 'Home', url: '/', priority: 1.0, changefreq: 'weekly' },
    { page: 'Tools', url: '/tools', priority: 0.9, changefreq: 'weekly' },
    { page: 'Character Counter', url: '/character-counter', priority: 0.9, changefreq: 'weekly' },
    { page: 'Text Case Converter', url: '/text-case-convert', priority: 0.9, changefreq: 'weekly' },
    { page: 'About', url: '/about', priority: 0.8, changefreq: 'monthly' },
    { page: 'Blog', url: '/blog', priority: 0.8, changefreq: 'weekly' },
    { page: 'Contact', url: '/contact', priority: 0.7, changefreq: 'monthly' },
    { page: 'FAQ', url: '/faq', priority: 0.7, changefreq: 'monthly' },
    { page: 'Privacy', url: '/privacy', priority: 0.5, changefreq: 'yearly' },
    { page: 'Terms', url: '/terms', priority: 0.5, changefreq: 'yearly' },
    { page: 'Disclaimer', url: '/disclaimer', priority: 0.5, changefreq: 'yearly' },
    { page: 'Cookies', url: '/cookies', priority: 0.5, changefreq: 'yearly' }
  ];

  return staticRoutes.map(route => ({
    url: route.url,
    changefreq: route.changefreq,
    priority: route.priority
  }));
}

// Function to get blog posts from JSON export
function getBlogPosts() {
  try {
    console.log('Loading blog posts from JSON export...');
    
    // Read blog data from JSON file (generated by export-blog-data.mjs)
    const jsonPath = join(__dirname, 'blog-data.json');
    const blogData = JSON.parse(readFileSync(jsonPath, 'utf8'));
    
    console.log(`✅ Loaded ${blogData.length} blog posts from JSON export`);
    
    return blogData.map(post => ({
      url: `/blog/${post.slug}`,
      changefreq: 'monthly',
      priority: 0.6,
      lastmod: post.publishDate ? new Date(post.publishDate).toISOString() : new Date('2025-01-01').toISOString()
    }));
  } catch (error) {
    console.error('❌ Failed to extract blog posts:', error.message);
    console.log('⚠️  Sitemap will be generated without blog posts');
    return [];
  }
}

// Function to generate robots.txt
function generateRobotsTxt() {
  const robotsContent = `User-agent: *
Allow: /

# Disallow admin, API, and internal areas
Disallow: /admin/
Disallow: /api/
Disallow: /drafts/
Disallow: /*.pdf$

# Set crawl delay for general bots
Crawl-delay: 1

# Sitemap location
Sitemap: ${SITE_URL}/sitemap.xml
`;

  writeFileSync(join(DIST_PUBLIC_PATH, 'robots.txt'), robotsContent);
  console.log('✅ Generated robots.txt');
}

// Main function to generate sitemap
async function generateSitemap() {
  try {
    console.log('🚀 Generating sitemap and robots.txt...');

    // Get all URLs
    const staticPages = getStaticPages();
    const blogPosts = getBlogPosts();
    const allUrls = [...staticPages, ...blogPosts];

    console.log(`📄 Static pages: ${staticPages.length}`);
    console.log(`📝 Blog posts: ${blogPosts.length}`);
    console.log(`🔗 Total URLs: ${allUrls.length}`);

    // Create sitemap stream
    const sitemapStream = new SitemapStream({ hostname: SITE_URL });
    const writeStream = createWriteStream(join(DIST_PUBLIC_PATH, 'sitemap.xml'));
    
    sitemapStream.pipe(writeStream);

    // Add all URLs to sitemap
    allUrls.forEach(urlData => {
      sitemapStream.write(urlData);
    });

    sitemapStream.end();

    // Wait for sitemap generation to complete
    await streamToPromise(sitemapStream);
    
    console.log('✅ Generated sitemap.xml');

    // Generate robots.txt
    generateRobotsTxt();

    console.log('🎉 Sitemap generation completed successfully!');
    console.log(`📍 Files generated in: ${DIST_PUBLIC_PATH}`);

  } catch (error) {
    console.error('❌ Error generating sitemap:', error);
    process.exit(1);
  }
}

// Run the script
generateSitemap();
